name: wardrobe_flutter
description: "衣柜"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^4.0.4
  permission_handler: 8.2.4
  path_provider: ^2.0.0
  flutter_screenutil: ^5.7.0
  flutter_easyloading: 3.0.5
  flutter_swiper_view: ^1.1.8
  flutter_animate: ^4.5.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  shared_preferences: ^2.2.3
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: AlibabaHealthFont
      fonts:
        - asset: assets/fonts/AlibabaHealthFont2.0CN-45R.ttf

    - family: pingfangfan
      fonts:
        - asset: assets/fonts/pingfangfan.ttf


  assets:
    - assets/images/
    - assets/icons/